Repository kaneki2109/Hacktoberfest-2022, pull requests merged in 2022-10, with the labels that each got.

#1 Create solution.py
  solution.py
Labels: documentation

#5 Create solution3.py
  solution3.py
Labels: help wanted, good first issue, hacktoberfest-accepted

#4 Create andimndi.txt
  andimndi.txt
Labels: help wanted, good first issue, hacktoberfest-accepted

#2 Create solution2.py
  solution2.py
Labels: help wanted, good first issue, hacktoberfest-accepted

#3 Create chlbsdk.txt
  chlbsdk.txt
Labels: help wanted, good first issue, hacktoberfest-accepted

#7 lodu.txt
  avinash.txt
  ddy.txt
  lodu.txt
  maihudon.txt
Labels: good first issue, hacktoberfest-accepted

#8 Create ddx.txt
  ddx.txt
Labels: good first issue, hacktoberfest-accepted

#12 Create Dslrfile.txt
  Amontrz.txt
Labels: good first issue, hacktoberfest-accepted

#13 Create flash.txt
  flash.txt
Labels: good first issue, hacktoberfest-accepted

#14 Create success.txt
  success.txt
Labels: good first issue, hacktoberfest-accepted

#15 Create start.txt
  start.txt
Labels: good first issue, hacktoberfest-accepted

#16 Create Ace.txt
  Ace.txt
Labels: good first issue, hacktoberfest-accepted

#17 Create copter.txt
  copter.txt
Labels: good first issue, hacktoberfest-accepted

#10 Update ddx.txt
  ddx.txt
Labels: good first issue, hacktoberfest-accepted

#18 Bubble sort in java
  bubble.java
Labels: good first issue, hacktoberfest-accepted

#19 Merge Sort Algorithm added
  mergesort.java
Labels: good first issue, hacktoberfest-accepted
